import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './compnents/NavBar'
import { SessionProvider } from 'next-auth/react'
import Provider from './provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Provider>
          <body className={inter.className}>
              <Navbar />
                <main>
                    {children}
                </main>
            </body>
        </Provider>
    </html>
  )
}
